import { Manifest } from '../generator';

// ── Types ─────────────────────────────────────────────────────────────────────
interface BuildContext {
    ids:        Set<string>;
    hasDb:      boolean;
    hasAuth:    boolean;
    hasMail:    boolean;
    hasSock:    boolean;
    hasPdf:     boolean;
    hasObserve: boolean;
    dbDriver:   string;
    name:       string;
}

function ctx(manifests: Manifest[], dbDriver: string, projectName: string): BuildContext {
    const ids = new Set(manifests.map(m => m.id));
    return {
        ids,
        hasDb:      ids.has('database'),
        hasAuth:    ids.has('auth'),
        hasMail:    ids.has('mailer'),
        hasSock:    ids.has('socket'),
        hasPdf:     ids.has('pdf'),
        hasObserve: ids.has('observe'),
        dbDriver,
        name: projectName,
    };
}

// ────────────────────────────────────────────────────────────────────────────
// Root .claude/CLAUDE.md — navigator + critical patterns (kept tight)
// ────────────────────────────────────────────────────────────────────────────
export function buildClaudeMd(manifests: Manifest[], dbDriver: string, projectName: string): string {
    const c = ctx(manifests, dbDriver, projectName);
    const l: string[] = [];

    l.push(`# ${c.name} — Development Guide`);
    l.push(``, `Generated by \`create-nestkit\`. New code should follow the patterns below unless there's a`);
    l.push(`reason not to — see "Starting Point, Not a Contract" below before deviating.`);
    l.push(``, `> **Detailed docs live next to the code** — read the \`CLAUDE.md\` inside each \`src/\` subdirectory.`);
    l.push(`> Claude Code loads them automatically when you work in that area.`);

    // Flexible-base philosophy — explicit so Claude Code (or a human) doesn't treat the
    // generated rules as immutable. Deviations are fine; silent, unrecorded drift isn't.
    l.push(``, `## Starting Point, Not a Contract`);
    l.push(`\`create-nestkit\` generated this project's structure and conventions once, at t=0. It does not`);
    l.push(`keep them in sync afterward — that's on whoever builds this project from here, human or Claude.`);
    l.push(`Deviating from \`.claude/rules/*.md\` is fine (swap a pattern, restructure a module, drop a plugin's`);
    l.push(`convention) — what's not fine is deviating silently:`);
    l.push(``);
    l.push(`1. **Log it** in \`.claude/context/decisions.md\` — what changed and why. Append, don't rewrite history.`);
    l.push(`2. **If it's a lasting convention** (not a one-off), update the matching \`.claude/rules/*.md\` file too.`);
    l.push(`   A rule that lies about the codebase is worse than no rule.`);
    l.push(``);
    l.push(`Save non-trivial implementation plans to \`.claude/context/plans/\` before executing them, so the`);
    l.push(`next session (or the next person) can see why something was built the way it was.`);

    // Canonical examples — only point at code that actually exists in this project.
    // users/roles only ship with the Auth plugin (not Database alone).
    l.push(``, `## Canonical Examples — Read These First`);
    if (c.hasAuth) {
        l.push(`- \`src/modules/users/\` — full CRUD module (entity → DTO → service → controller → exceptions)`);
        l.push(`- \`src/app/auth/\` — JWT auth, guards, decorators, UserForAuthDto`);
        l.push(`- \`src/modules/roles/\` — simpler CRUD (no email/password, no relations)`);
    } else if (c.hasDb) {
        l.push(`- No domain module exists yet. Run \`/nestjs/module <Name>\` to scaffold the first one —`);
        l.push(`  it follows the pattern in \`.claude/rules/database.md\`.`);
    } else {
        l.push(`- This is a bare scaffold — no domain modules, no database. See \`.claude/rules/*.md\` for the`);
        l.push(`  patterns each active plugin brings; there's no CRUD convention to follow until Database is added.`);
    }

    // Active plugins
    l.push(``, `## Active Plugins`);
    if (!c.hasDb && !c.hasAuth && !c.hasMail && !c.hasSock && !c.hasPdf && !c.hasObserve) {
        l.push(`- None — core only (config, health check, Swagger, global exception filter).`);
    } else {
        if (c.hasDb)      l.push(`- **Database** (${c.dbDriver}) — TypeORM, migrations, seeds → \`src/database/CLAUDE.md\``);
        if (c.hasAuth)    l.push(`- **Auth** — JWT + refresh rotation + roles → \`src/app/auth/CLAUDE.md\``);
        if (c.hasMail)    l.push(`- **Mailer** — SMTP or API adapter → \`src/plugins/CLAUDE.md\``);
        if (c.hasSock)    l.push(`- **WebSockets** — Socket.io → \`src/plugins/CLAUDE.md\``);
        if (c.hasPdf)     l.push(`- **PDF** — Puppeteer → \`src/plugins/CLAUDE.md\``);
        if (c.hasObserve) l.push(`- **Observability** — Nest Observe → \`src/config/CLAUDE.md\` (needs credentials from observe.nestjs.com)`);
    }

    // Commands
    l.push(``, `## Commands`, `\`\`\`bash`);
    l.push(`npm run start:dev      # development with watch`);
    l.push(`npm run build          # compile TypeScript`);
    if (c.hasDb) {
        l.push(`npm run migration:generate -- src/database/migrations/<name>`);
        l.push(`npm run migration:run`);
        l.push(`npm run seed           # insert root user (first run only)`);
    }
    l.push(`\`\`\``);

    // Structure
    l.push(``, `## Project Structure`, `\`\`\``);
    l.push(`src/`);
    l.push(`├── app/        # Logic modules — no own DB table (${c.hasAuth ? 'auth, ' : ''}health)`);
    if (c.hasDb) l.push(`├── modules/    # Domain modules — one folder = one DB table`);
    if (c.hasMail || c.hasSock || c.hasPdf)
        l.push(`├── plugins/    # Port & Adapter (${[c.hasMail && 'mailer', c.hasSock && 'socket', c.hasPdf && 'pdf'].filter(Boolean).join(', ')})`);
    if (c.hasDb) l.push(`├── database/   # TypeORM config, base entity, migrations, seeds`);
    l.push(`├── config/     # @Global AppConfigModule, Joi env validation`);
    l.push(`└── shared/     # ${c.hasDb ? 'DtoRepository, ' : ''}swagger utils, filters, DTOs`);
    l.push(`\`\`\``);

    if (c.hasDb) {
        // Module anatomy
        l.push(``, `---`, ``, `## Module Anatomy — \`modules/{name}s/\``);
        l.push(`\`\`\``);
        l.push(`├── entities/{name}.entity.ts       # extends BaseEntitySoftDelete`);
        l.push(`├── dto/{name}.dto.ts               # @DtoField / @DtoRelation`);
        l.push(`├── dto/create-{name}.dto.ts`);
        l.push(`├── dto/update-{name}.dto.ts`);
        l.push(`├── dto/find-all-{name}s-params.dto.ts    # extends PaginationParamsDto`);
        l.push(`├── dto/find-all-{name}s-response.dto.ts  # extends PaginationResponseDto<Dto>`);
        l.push(`├── services/{name}s.service.ts`);
        l.push(`├── controllers/{name}s.controller.ts`);
        l.push(`├── exceptions/{name}-not-found.exception.ts`);
        l.push(`├── exceptions/{name}-already-exists.exception.ts`);
        l.push(`├── exceptions/index.ts`);
        l.push(`└── {name}s.module.ts`);
        l.push(`\`\`\``);

        // Service pattern
        l.push(``, `---`, ``, `## Service Pattern — CRITICAL`);
        l.push(c.hasAuth
            ? `Full reference: \`src/modules/users/services/users.service.ts\``
            : `Follow this pattern for every service you add (no existing module to point at yet):`);
        l.push(``);
        l.push(`\`\`\`typescript`);
        l.push(`// DTO class is ALWAYS the first argument`);
        l.push(`findAll<T>(dto, params)                          // → PaginationResponseDto<T>`);
        l.push(`findOne<T>(dto, where, { throwException: false}) // → T | null`);
        l.push(`findOne<T>(dto, where, options?)                 // → T  (throws if missing)`);
        l.push(`findOneById<T>(dto, id, options?)`);
        l.push(`// Add findOneBy<Field> only when that field exists on this entity`);
        l.push(``);
        l.push(`create<T>(returnDto, createDto, options?)        // → T`);
        l.push(`update<T>(returnDto, id, updateDto, options?)    // → T`);
        l.push(`remove(id, options?)                             // void`);
        l.push(`\`\`\``);
        l.push(`- Existence check → \`rawRepo.existsBy(where)\` (SELECT 1, no DTO overhead)`);
        l.push(`- Create → \`repo.create()\` + explicit field assignment (no spread)`);
        l.push(`- Return → \`new DtoRepository(repo).findOne({ dto: returnDto, where: { id } })\` (transaction-safe)`);
        l.push(`- All in \`src/shared/CLAUDE.md\` → DtoRepository, MutationOptions, FindOptions, pagination`);
    }

    // Controller pattern — general Nest/Swagger convention, applies even without a database
    // (webhook receivers, PDF endpoints, etc. still need consistent Swagger + error handling).
    l.push(``, `---`, ``, `## Controller Pattern — CRITICAL`);
    if (c.hasAuth) l.push(`Full reference: \`src/modules/users/controllers/users.controller.ts\``, ``);
    l.push(`\`\`\`typescript`);
    l.push(`import { ApiNotFound, ApiUnauthorized, ApiConflict } from 'src/shared/utils/swagger';`);
    if (c.hasAuth) l.push(`import { AdminUp, RootOnly, UserUp } from 'src/app/auth/decorators';`);
    l.push(`/**`);
    l.push(` * Error dictionary: X_NOT_FOUND 404, X_ALREADY_EXISTS 409`);
    if (c.hasAuth) l.push(` *   INVALID_TOKEN 401, INSUFFICIENT_PERMISSIONS 403`);
    l.push(` */`);
    l.push(`@ApiTags('...') @ApiBearerAuth('access-token') @Controller('...')`);
    l.push(`export class XController {`);
    l.push(`    @Get(':id')${c.hasAuth ? ' @AdminUp()' : ''}`);
    l.push(`    @ApiOperation({ summary: '...', description: '...' })`);
    l.push(`    @ApiOkResponse({ type: XDto })`);
    l.push(`    @ApiNotFound({ code: 'X_NOT_FOUND', message: 'X not found.' })`);
    l.push(`    @ApiUnauthorized({ code: 'INVALID_TOKEN', message: 'Invalid or expired token.' })`);
    l.push(`    async findOne(@Param('id', ParseIntPipe) id: number): Promise<XDto> {`);
    l.push(`        return await this.service.findOneById(XDto, id);`);
    l.push(`    }`);
    l.push(`}`);
    l.push(`\`\`\``);
    l.push(`- \`async\` + \`return await\` on every method`);
    l.push(`- Error decorators are variadic: \`@ApiNotFound(err1, err2)\` shows dropdown in Swagger for multiple codes`);
    l.push(`- \`'access-token'\` = security scheme name from \`src/config/helpers/swagger.ts\``);
    l.push(`- Full swagger util reference → \`src/shared/CLAUDE.md\``);

    // Exception pattern
    l.push(``, `---`, ``, `## Exception Pattern`);
    l.push(`All exceptions → \`{ statusCode, error, message, path, timestamp }\` via HttpExceptionFilter.`);
    l.push(`The \`error\` field (SCREAMING_SNAKE_CASE) is what the frontend uses to distinguish same-status errors.`, ``);
    l.push(`\`\`\`typescript`);
    l.push(`export class XNotFoundException extends NotFoundException {`);
    l.push(`    constructor() { super({ message: 'X not found.', error: 'X_NOT_FOUND' }); }`);
    l.push(`}`);
    l.push(`\`\`\``);
    l.push(`- One class per exception, one file per class, barrel in \`exceptions/index.ts\``);
    l.push(`- **Never** throw NestJS built-ins inline in services — always use the exception class`);

    // Slash commands
    l.push(``, `---`, ``, `## Slash Commands`);
    if (c.hasDb) l.push(`- \`/nestjs/module <Name>\`         — scaffold complete CRUD module (entity + TypeORM)`);
    l.push(`- \`/nestjs/exception <Mod> <Type>\` — add exception to a module`);
    l.push(`- \`/nestjs/plugin <Name> <Adapter>\` — scaffold port/adapter plugin`);
    if (c.hasDb) l.push(`- \`/db/map\`                       — map a DB schema to modules interactively`);

    // @imports — Claude Code loads these files into context from .claude/rules/
    l.push(``, `---`, ``);
    l.push(`@.claude/rules/shared.md`);
    l.push(`@.claude/rules/config.md`);
    if (c.hasDb)   l.push(`@.claude/rules/database.md`);
    if (c.hasAuth) l.push(`@.claude/rules/auth.md`);
    if (c.hasMail || c.hasSock || c.hasPdf) l.push(`@.claude/rules/plugins.md`);

    return l.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────────────
// src/shared/CLAUDE.md — all shared utilities
// ────────────────────────────────────────────────────────────────────────────
export function buildSharedClaudeMd(c: ReturnType<typeof ctx>): string {
    const l: string[] = [];

    l.push(`# shared/ — Utilities Reference`);
    l.push(``, `Everything in \`src/shared/\` is usable from any module. Nothing here imports from \`modules/\` or \`app/\`.`);

    if (c.hasDb) {
        l.push(``, `## DtoRepository (\`src/shared/orm\`)`);
        l.push(`Wraps TypeORM \`Repository<E>\` with automatic SELECT + JOIN derived from the DTO class.`);
        l.push(`\`\`\`typescript`);
        l.push(`private readonly repo: DtoRepository<User>;`);
        l.push(`constructor(@InjectRepository(User) private readonly rawRepo: Repository<User>) {`);
        l.push(`    this.repo = new DtoRepository(rawRepo);`);
        l.push(`}`);
        l.push(`// Usage`);
        l.push(`const result = await this.repo.findOne({ dto: UserDto, where: { id } });`);
        l.push(`const page   = await this.repo.findPaginated({ dto: UserDto, pagination: params, where: {}, order: {} });`);
        l.push(`// In mutations — builds from the same repo for transaction safety:`);
        l.push(`const saved = await repo.save(entity);`);
        l.push(`return (await new DtoRepository(repo).findOne({ dto: returnDto, where: { id: saved.id } }))!;`);
        l.push(`\`\`\``);

        l.push(``, `## @DtoField and @DtoRelation`);
        l.push(`Decorators that drive both TypeORM SELECT and class-transformer serialization.`);
        l.push(`\`\`\`typescript`);
        l.push(`import { DtoField, DtoRelation } from 'src/shared/orm';`);
        l.push(``);
        l.push(`export class ProductDto {`);
        l.push(`    @DtoField() id!: number;           // scalar → SELECT product_id`);
        l.push(`    @DtoField() name!: string;          // scalar → SELECT name`);
        l.push(`    @DtoField() createdAt!: Date;`);
        l.push(`    @DtoRelation(() => CategoryDto)     // relation → LEFT JOIN categories`);
        l.push(`    category!: CategoryDto;`);
        l.push(`}`);
        l.push(`\`\`\``);
        l.push(`Only \`@DtoField\` / \`@DtoRelation\` fields are included in SELECT — adding a field to the DTO automatically includes it in all queries.`);

        l.push(``, `## FindOptions and MutationOptions`);
        l.push(`\`\`\`typescript`);
        l.push(`import { FindOptions, MutationOptions } from 'src/shared/dto';`);
        l.push(``);
        l.push(`// FindOptions`);
        l.push(`{ throwException?: boolean }  // false = return null instead of throwing NotFoundException`);
        l.push(``);
        l.push(`// MutationOptions`);
        l.push(`{ manager?: EntityManager, hardDelete?: boolean }`);
        l.push(`// manager  = pass an EntityManager to run inside an existing transaction`);
        l.push(`// hardDelete = true → repo.delete(), false (default) → repo.softDelete()`);
        l.push(`\`\`\``);
    }

    l.push(``, `## Pagination`);
    l.push(`Generic — usable for any list endpoint, DB-backed or not.`);
    l.push(`\`\`\`typescript`);
    l.push(`// Params DTO`);
    l.push(`export class FindAllProductsParamsDto extends PaginationParamsDto { ... }`);
    l.push(`// PaginationParamsDto has: page (default 1), limit (default 10)`);
    l.push(``);
    l.push(`// Response DTO`);
    l.push(`export class FindAllProductsResponseDto extends PaginationResponseDto<ProductDto> {`);
    l.push(`    @ApiProperty({ type: [ProductDto] }) declare data: ProductDto[];`);
    l.push(`}`);
    l.push(`// PaginationResponseDto has: data[], meta: { page, limit, total, pages }`);
    l.push(`\`\`\``);

    l.push(``, `## Swagger Response Decorators (\`src/shared/utils/swagger\`)`);
    l.push(`All decorators are **variadic** — pass one or many \`{ code, message }\` objects.`);
    l.push(`Multiple errors for the same status produce a dropdown in Swagger UI.`);
    l.push(`\`\`\`typescript`);
    l.push(`import { ApiNotFound, ApiConflict, ApiUnauthorized, ApiForbidden,`);
    l.push(`         ApiValidationError, ApiUnprocessableEntity } from 'src/shared/utils/swagger';`);
    l.push(``);
    l.push(`@ApiNotFound({ code: 'PRODUCT_NOT_FOUND', message: 'Product not found.' })`);
    l.push(`@ApiConflict({ code: 'PRODUCT_ALREADY_EXISTS', message: 'A product with this name already exists.' })`);
    l.push(`@ApiUnauthorized({ code: 'INVALID_TOKEN', message: 'Invalid or expired token.' })`);
    l.push(`@ApiForbidden({ code: 'INSUFFICIENT_PERMISSIONS', message: 'You do not have permission.' })`);
    l.push(`@ApiValidationError()  // 400 — class-validator format (always no-args)`);
    l.push(``);
    l.push(`// Multiple codes for same status:`);
    l.push(`@ApiUnauthorized(`);
    l.push(`    { code: 'INVALID_TOKEN',       message: 'Invalid or expired token.' },`);
    l.push(`    { code: 'INVALID_CREDENTIALS', message: 'Invalid credentials.' },`);
    l.push(`)`);
    l.push(`\`\`\``);
    l.push(`Response body shape (all non-400): \`{ statusCode, error, message, path, timestamp }\``);

    l.push(``, `## HttpExceptionFilter`);
    l.push(`Global filter in \`src/shared/filters/http-exception.filter.ts\`.`);
    l.push(`Normalizes ALL HttpExceptions to: \`{ statusCode, error, message, path, timestamp }\`.`);
    l.push(`- When you pass \`{ message, error }\` to an exception constructor → \`error\` is your domain code.`);
    l.push(`- When you pass a plain string → \`error\` falls back to the HTTP status code label (e.g., \`NOT_FOUND\`).`);
    l.push(`- 500s are logged with stack trace; lower statuses are not.`);

    if (c.hasAuth) {
        l.push(``, `## @CurrentUser Decorator`);
        l.push(`\`\`\`typescript`);
        l.push(`import { CurrentUser } from 'src/shared/decorators';`);
        l.push(`import type { AuthUser } from 'src/app/auth/strategies/jwt.strategy';`);
        l.push(``);
        l.push(`// In a controller method:`);
        l.push(`async logout(@CurrentUser() user: AuthUser): Promise<void>`);
        l.push(`async getProfile(@CurrentUser('id') id: number): Promise<UserDto>`);
        l.push(`// AuthUser = { id, email, roleId } — what JwtStrategy puts in req.user`);
        l.push(`\`\`\``);
    }

    l.push(``, `## Other Shared Utilities`);
    l.push(`- \`src/shared/utils/crypto.util.ts\` → \`hashPassword(plain)\`, \`comparePassword(plain, hash)\` (bcrypt)`);
    l.push(`- \`src/shared/utils/code-generator.util.ts\` → \`generateCode(length)\` random alphanumeric`);
    l.push(`- \`src/shared/utils/transformers.util.ts\` → \`transformToBoolean(value, name)\` for query params`);
    l.push(`- \`src/shared/dto/error-response.dto.ts\` → Swagger schema for error responses`);
    l.push(`- \`src/shared/enums/environment.enum.ts\` → \`EnvironmentEnum\` (development, production, test, debug)`);

    return l.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────────────
// src/config/CLAUDE.md — config module and env vars
// ────────────────────────────────────────────────────────────────────────────
export function buildConfigClaudeMd(hasObserve: boolean): string {
    const l: string[] = [];

    l.push(`# config/ — Configuration Reference`);

    l.push(``, `## AppConfigModule (\`src/config/config.module.ts\`)`);
    l.push(`\`@Global()\` — providers exported here are available in every module without re-importing.`);
    l.push(`Loads \`.env\`, validates with Joi schema, and exposes \`AppConfig\` service.`);

    l.push(``, `## AppConfig (\`src/config/services/app.config.ts\`)`);
    l.push(`\`\`\`typescript`);
    l.push(`import { AppConfig } from 'src/config/services/app.config';`);
    l.push(``);
    l.push(`constructor(private readonly config: AppConfig) {}`);
    l.push(`// Available properties:`);
    l.push(`config.nodeEnv        // EnvironmentEnum`);
    l.push(`config.port           // number`);
    l.push(`config.apiPrefix      // string  (default: 'api')`);
    l.push(`config.corsOrigins    // string  ('*', or a comma-separated list of allowed origins)`);
    l.push(`\`\`\``);

    l.push(``, `## Adding New Env Vars`);
    l.push(`1. Add to \`src/config/env.validation.ts\` (Joi schema)`);
    l.push(`2. Add to \`.env.example\``);
    l.push(`3. If needed, expose via a config service (create in \`src/config/services/\`)`);
    l.push(`\`\`\`typescript`);
    l.push(`// env.validation.ts — append:`);
    l.push(`MY_VAR: Joi.string().required(),`);
    l.push(`MY_OPT: Joi.number().default(42),`);
    l.push(`\`\`\``);

    l.push(``, `## Environment Helpers`);
    l.push(`- \`getEnvSettings(nodeEnv)\` → \`{ logger: LogLevel[], swagger: boolean }\``);
    l.push(`  - \`development/debug\` → swagger enabled, verbose logging`);
    l.push(`  - \`production\` → swagger disabled, error-only logging`);
    l.push(`- \`getCorsOptions(corsOrigins)\` → Express CORS config`);
    l.push(`- \`setupSwagger(app, options)\` → configures OpenAPI at \`/api/docs\` with bearer auth`);
    l.push(`  - Bearer scheme name: \`'access-token'\` → use \`@ApiBearerAuth('access-token')\` in controllers`);
    l.push(`- \`logServerStatus(cfg, appName, opts)\` → prints the startup banner`);

    if (hasObserve) {
        l.push(``, `## Observability (\`src/config/helpers/observe.ts\`)`);
        l.push(`\`createObserveModule()\` returns \`{ ObserveModule, ObserveInstrument }\`, wired in exactly two places:`);
        l.push(`\`\`\`typescript`);
        l.push(`// app.module.ts`);
        l.push(`ObserveModule.forRoot({ appKey: process.env.OBSERVE_APP_KEY!, appSecret: ..., serviceId: ... })`);
        l.push(``);
        l.push(`// main.ts`);
        l.push(`NestFactory.create(AppModule, { logger, instrument: ObserveInstrument })`);
        l.push(`\`\`\``);
        l.push(`Credentials come from \`OBSERVE_APP_KEY\` / \`OBSERVE_APP_SECRET\` (sign up at`);
        l.push(`[observe.nestjs.com](https://observe.nestjs.com)) — read directly from \`process.env\`, not via`);
        l.push(`\`ConfigService\`, because \`ObserveModule.forRoot()\` needs them at module-registration time,`);
        l.push(`before Nest's DI container exists. \`dotenv/config\` at the top of \`main.ts\` guarantees they're`);
        l.push(`already loaded by then. Missing/invalid credentials don't crash the app — the collector just`);
        l.push(`returns 401 and telemetry is dropped.`);
    }

    return l.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────────────
// src/database/CLAUDE.md — TypeORM, migrations, base entity
// ────────────────────────────────────────────────────────────────────────────
export function buildDatabaseClaudeMd(dbDriver: string): string {
    const l: string[] = [];

    l.push(`# database/ — TypeORM Reference`);
    l.push(``, `Driver: \`${dbDriver}\`. All config comes from env vars (see \`src/config/CLAUDE.md\`).`);

    l.push(``, `## BaseEntitySoftDelete (\`src/database/entities/base.entity.ts\`)`);
    l.push(`All entities must extend this. It provides:`);
    l.push(`\`\`\`typescript`);
    l.push(`createdAt: Date   // @CreateDateColumn`);
    l.push(`updatedAt: Date   // @UpdateDateColumn`);
    l.push(`deletedAt: Date   // @DeleteDateColumn — set by softDelete(), null for active records`);
    l.push(`\`\`\``);
    l.push(`TypeORM automatically excludes soft-deleted rows from all \`find*()\` queries.`);
    l.push(`Use \`{ withDeleted: true }\` to include them.`);

    l.push(``, `## Entity Conventions`);
    l.push(`\`\`\`typescript`);
    l.push(`@Entity('products')   // table name: snake_case plural`);
    l.push(`export class Product extends BaseEntitySoftDelete {`);
    l.push(`    @PrimaryGeneratedColumn({ name: 'product_id' }) id: number;   // always {entity}_id in DB`);
    l.push(`    @Column({ name: 'name', type: 'varchar', length: 150 }) name: string;`);
    l.push(`    @Column({ name: 'category_id', type: 'int' }) categoryId: number;`);
    l.push(`    @ManyToOne(() => Category, cat => cat.products)`);
    l.push(`    @JoinColumn({ name: 'category_id' })             // FK column must have @JoinColumn`);
    l.push(`    category: Category;`);
    l.push(`}`);
    l.push(`\`\`\``);

    l.push(``, `## Migrations`);
    l.push(`\`\`\`bash`);
    l.push(`# Generate — compares entities vs DB schema:`);
    l.push(`npm run migration:generate -- src/database/migrations/<DescriptiveName>`);
    l.push(`# Run all pending:`);
    l.push(`npm run migration:run`);
    l.push(`# Revert last:`);
    l.push(`npm run migration:revert`);
    l.push(`\`\`\``);
    l.push(`Config: \`src/database/config/data-source.ts\`.`);
    l.push(`Never use \`synchronize: true\` in any environment — always use migrations.`);

    l.push(``, `## Transactions via MutationOptions`);
    l.push(`\`\`\`typescript`);
    l.push(`// In a higher-level service that coordinates two modules:`);
    l.push(`await dataSource.transaction(async (manager) => {`);
    l.push(`    await usersService.create(UserDto, dto, { manager });`);
    l.push(`    await ordersService.create(OrderDto, orderDto, { manager });`);
    l.push(`});`);
    l.push(`// Both mutations share the same transaction — if one fails, both roll back.`);
    l.push(`// DtoRepository(repo) in each service uses the manager-bound repo automatically.`);
    l.push(`\`\`\``);

    l.push(``, `## Seed (\`src/database/seeds/seed.ts\`)`);
    l.push(`Run standalone via \`npm run seed\`. Idempotent — skips if root user already exists.`);
    l.push(`Controlled by env vars: \`SEED_ROOT_EMAIL\`, \`SEED_ROOT_PASSWORD\`.`);
    l.push(`Adapt the seed if the users table has different fields.`);

    return l.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────────────
// src/app/auth/CLAUDE.md — auth patterns (only when auth plugin selected)
// ────────────────────────────────────────────────────────────────────────────
export function buildAuthClaudeMd(): string {
    const l: string[] = [];

    l.push(`# app/auth/ — Auth Reference`);
    l.push(``, `JWT authentication with refresh token rotation. Refresh tokens are stored hashed — never in plain text.`);

    l.push(``, `## Guards (applied globally via APP_GUARD in auth.module.ts)`);
    l.push(`- **JwtAuthGuard** — verifies the JWT on every request. Routes marked \`@Public()\` are exempt.`);
    l.push(`- **RolesGuard** — checks \`user.roleId <= requiredRole\`. Routes without \`@RootOnly/AdminUp/UserUp\` are exempt.`);
    l.push(`Both guards are registered as \`APP_GUARD\` — removing \`AuthModule\` from \`AppModule\` disables them globally.`);

    l.push(``, `## Decorators`);
    l.push(`\`\`\`typescript`);
    l.push(`import { Public, CurrentUser } from 'src/app/auth/decorators';`);
    l.push(`import { AdminUp, RootOnly, UserUp, Roles } from 'src/app/auth/decorators';`);
    l.push(`import type { AuthUser } from 'src/app/auth/strategies/jwt.strategy';`);
    l.push(``);
    l.push(`@Public()            // bypass JwtAuthGuard for this route`);
    l.push(`@RootOnly()          // roleId must be 1 (root) — also adds @ApiForbiddenResponse`);
    l.push(`@AdminUp()           // roleId must be ≤ 2 (admin or root)`);
    l.push(`@UserUp()            // roleId must be ≤ 3 (any authenticated user)`);
    l.push(`// In controllers always use the above — never raw @Roles(n)`);
    l.push(``);
    l.push(`@CurrentUser()               // → AuthUser = { id, email, roleId }`);
    l.push(`@CurrentUser('id')           // → number`);
    l.push(`@CurrentUser('roleId')       // → number`);
    l.push(`\`\`\``);

    l.push(``, `## JWT Payload and AuthUser`);
    l.push(`\`\`\`typescript`);
    l.push(`// What is signed into the token (JwtPayload):`);
    l.push(`{ sub: number, email: string, roleId: number }`);
    l.push(``);
    l.push(`// What JwtStrategy puts into req.user (AuthUser):`);
    l.push(`{ id: number, email: string, roleId: number }`);
    l.push(`\`\`\``);

    l.push(``, `## UserForAuthDto — internal auth DTO`);
    l.push(`\`\`\`typescript`);
    l.push(`import { UserForAuthDto } from 'src/modules/users/dto/user-for-auth.dto';`);
    l.push(``);
    l.push(`// Used in auth.service.ts — includes password and refreshToken`);
    l.push(`const user = await usersService.findOneByEmail(UserForAuthDto, email, { throwException: false });`);
    l.push(`// user.password, user.refreshToken are available`);
    l.push(``);
    l.push(`// NEVER return UserForAuthDto in an HTTP response.`);
    l.push(`// For public-facing user data always use UserDto.`);
    l.push(`\`\`\``);

    l.push(``, `## Token Rotation (refresh)`);
    l.push(`1. Client sends refresh token → server verifies signature and expiry.`);
    l.push(`2. Server compares \`bcrypt.compare(refreshToken, user.refreshToken)\` (stored as hash).`);
    l.push(`3. If match → issue new access + refresh pair, revoke old refresh token.`);
    l.push(`4. If mismatch (reuse detected) → revoke ALL sessions (\`setRefreshToken(id, null)\`).`);
    l.push(`Access tokens expire in \`JWT_TIME_EXPIRE\` (default 15m). Refresh tokens in \`JWT_REFRESH_TIME_EXPIRE\` (default 7d).`);

    l.push(``, `## Malleability — Adapting to a Different Users Table`);
    l.push(`If the users table doesn't have \`email\` / \`password\` (e.g., uses \`username\`):`);
    l.push(`1. Update \`UserForAuthDto\` fields to match the auth fields you need.`);
    l.push(`2. Update \`auth.service.ts login()\` — replace \`findOneByEmail\` with the appropriate lookup.`);
    l.push(`3. Keep everything else (JWT, rotation, guards, decorators) as-is.`);
    l.push(`Role hierarchy numbers (1/2/3) can be changed in \`RoleEntity\` + seed + guard comparison.`);

    l.push(``, `## Auth Exceptions (\`src/app/auth/exceptions/\`)`);
    l.push(`- \`InvalidCredentialsException\` → 401 \`INVALID_CREDENTIALS\``);
    l.push(`- \`InvalidRefreshTokenException\` → 401 \`INVALID_REFRESH_TOKEN\``);
    l.push(`- \`InvalidTokenException\` → 401 \`INVALID_TOKEN\` (thrown by JwtAuthGuard)`);
    l.push(`- \`InsufficientPermissionsException\` → 403 \`INSUFFICIENT_PERMISSIONS\` (thrown by RolesGuard)`);

    return l.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────────────
// src/plugins/CLAUDE.md — port/adapter pattern and plugin APIs
// ────────────────────────────────────────────────────────────────────────────
export function buildPluginsClaudeMd(c: ReturnType<typeof ctx>): string {
    const l: string[] = [];

    l.push(`# plugins/ — Port & Adapter Reference`);
    l.push(``, `Plugins follow the Port & Adapter pattern — consumers inject the port (abstract class), never the concrete adapter.`);
    l.push(`Swapping implementations (e.g., SMTP → Resend) requires zero changes to business code.`);

    l.push(``, `## Plugin Structure`);
    l.push(`\`\`\``);
    l.push(`plugins/{name}/`);
    l.push(`├── {name}.port.ts           # abstract class — the contract`);
    l.push(`├── {name}.module.ts         # @Global() DynamicModule.register()`);
    l.push(`├── exceptions/              # plugin-specific exception classes`);
    l.push(`└── {adapter}/`);
    l.push(`    ├── {adapter}.adapter.ts # extends port`);
    l.push(`    ├── {adapter}.config.ts  # reads env vars via ConfigService`);
    l.push(`    └── {adapter}.module.ts  # provides adapter, exports port`);
    l.push(`\`\`\``);
    l.push(`Module.register() re-exports the adapter module — this makes the port globally injectable.`);

    if (c.hasMail) {
        l.push(``, `## Mailer Plugin`);
        l.push(`\`\`\`typescript`);
        l.push(`import { MailerPort, MailOptions } from 'src/plugins/mailer/mailer.port';`);
        l.push(``);
        l.push(`constructor(private readonly mailer: MailerPort) {}`);
        l.push(``);
        l.push(`// Fire-and-forget (errors are logged, not thrown)`);
        l.push(`this.mailer.send({`);
        l.push(`    to:      'user@example.com',`);
        l.push(`    subject: 'Welcome',`);
        l.push(`    html:    '<p>Hello!</p>',`);
        l.push(`    // text, template, context, attachments also available`);
        l.push(`});`);
        l.push(`\`\`\``);
        l.push(`Transport selected at startup via \`MAILER_TRANSPORT=smtp|api\` env var.`);
        l.push(`- SMTP: uses \`@nestjs-modules/mailer\` with Handlebars for templates.`);
        l.push(`- API: compatible with Resend by default — override \`buildPayload()\` for other providers.`);
    }

    if (c.hasSock) {
        l.push(``, `## Socket Plugin`);
        l.push(`\`\`\`typescript`);
        l.push(`import { SocketService } from 'src/plugins/socket/socket.service';`);
        l.push(``);
        l.push(`constructor(private readonly socket: SocketService) {}`);
        l.push(``);
        l.push(`this.socket.emit('user.created', { id: user.id });`);
        l.push(`// Namespace: WEBSOCKET_NAMESPACE env var (default: 'app')`);
        l.push(`\`\`\``);
    }

    if (c.hasPdf) {
        l.push(``, `## PDF Plugin`);
        l.push(`\`\`\`typescript`);
        l.push(`import { PdfPort, PdfOptions } from 'src/plugins/pdf/pdf.port';`);
        l.push(``);
        l.push(`constructor(private readonly pdf: PdfPort) {}`);
        l.push(``);
        l.push(`const buffer = await this.pdf.generate('<html>...</html>', {`);
        l.push(`    format: 'Letter',          // default`);
        l.push(`    printBackground: true,     // default`);
        l.push(`    margin: { top: '10mm' },`);
        l.push(`});`);
        l.push(`// Returns Buffer — stream to client or save to storage`);
        l.push(`\`\`\``);
        l.push(`Throws \`PdfGenerationException\` (500) on Puppeteer errors.`);
        l.push(`Puppeteer browser is launched once at module init and reused.`);
    }

    l.push(``, `## Adding a New Plugin`);
    l.push(`Use \`/nestjs/plugin <Name> <Adapter>\` slash command — it scaffolds the full port/adapter structure.`);
    l.push(`Key requirements:`);
    l.push(`- Port must be an \`abstract class\` (not interface) so NestJS DI can use it as a token.`);
    l.push(`- \`{Name}Module.register()\` returns \`{ module, imports: [adapterModule], exports: [adapterModule] }\`.`);
    l.push(`- Add env vars to \`.env.example\` and \`src/config/env.validation.ts\`.`);
    l.push(`- All errors → exception classes in \`exceptions/\`, never inline throws.`);

    return l.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────────────
// .claude/context/ — the project's own journal, as opposed to the generated rules.
// Seeded once; from here on it's maintained by whoever works on the project.
// ────────────────────────────────────────────────────────────────────────────
export function buildContextReadme(): string {
    const l: string[] = [];

    l.push(`# .claude/context/ — Project Journal`);
    l.push(``, `\`.claude/rules/\` describes how this project worked when \`create-nestkit\` generated it.`);
    l.push(`This folder is where that description gets kept honest as the project actually evolves.`);

    l.push(``, `## decisions.md`);
    l.push(`One entry per meaningful deviation from \`.claude/rules/*.md\`: a changed convention, a`);
    l.push(`plugin's pattern dropped, a structural change. Append-only — newest entry at the bottom.`);

    l.push(``, `## plans/`);
    l.push(`Save non-trivial implementation plans here **before** executing them — what's about to`);
    l.push(`change and why. The output of Claude Code's Plan mode belongs here. Name files by date`);
    l.push(`and topic: \`2026-03-14-migrate-mailer-to-resend.md\`.`);

    l.push(``, `## Why bother`);
    l.push(`A rules file that no longer matches the code is worse than no rules file — it actively`);
    l.push(`misleads the next person (or the next Claude Code session). When you deviate:`);
    l.push(``);
    l.push(`1. Log it here first.`);
    l.push(`2. If it's a lasting convention, update the relevant \`.claude/rules/*.md\` file too.`);

    return l.join('\n') + '\n';
}

export function buildDecisionsSeed(projectName: string): string {
    const l: string[] = [];

    l.push(`# Decisions Log — ${projectName}`);
    l.push(``, `Append one entry per meaningful deviation from \`.claude/rules/*.md\`. Newest at the bottom.`);
    l.push(`See \`.claude/context/README.md\` for what belongs here.`);
    l.push(``, `## Format`);
    l.push(`\`\`\`markdown`);
    l.push(`### YYYY-MM-DD — Short title`);
    l.push(`**What changed:** ...`);
    l.push(`**Why:** ...`);
    l.push(`**Rules updated:** yes/no — which file, if yes`);
    l.push(`\`\`\``);
    l.push(``, `---`);

    return l.join('\n') + '\n';
}

export function buildPlansReadme(): string {
    const l: string[] = [];

    l.push(`# Saved Plans`);
    l.push(``, `Drop non-trivial implementation plans here before executing them — a short markdown file`);
    l.push(`describing what's about to change and why. Useful for anyone (or any Claude Code session)`);
    l.push(`picking this project back up later.`);
    l.push(``, `Name files by date and topic, e.g. \`2026-03-14-migrate-mailer-to-resend.md\`.`);

    return l.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────────────
// Entry point — returns all files to generate as a map
// ────────────────────────────────────────────────────────────────────────────
export function buildAllClaudeFiles(
    manifests: Manifest[],
    dbDriver:  string,
    projectName: string,
): Map<string, string> {
    const c = ctx(manifests, dbDriver, projectName);
    const files = new Map<string, string>();

    // Root navigator — imports all rules files
    files.set('.claude/CLAUDE.md', buildClaudeMd(manifests, dbDriver, projectName));

    // All detailed rules live under .claude/rules/ — unified, nothing scattered in src/
    files.set('.claude/rules/shared.md',   buildSharedClaudeMd(c));
    files.set('.claude/rules/config.md',   buildConfigClaudeMd(c.hasObserve));

    if (c.hasDb)   files.set('.claude/rules/database.md', buildDatabaseClaudeMd(c.dbDriver));
    if (c.hasAuth) files.set('.claude/rules/auth.md',     buildAuthClaudeMd());
    if (c.hasMail || c.hasSock || c.hasPdf)
        files.set('.claude/rules/plugins.md', buildPluginsClaudeMd(c));

    // Project journal — separate from the generated rules above, meant to be written to
    // (not regenerated) as the project evolves. See buildContextReadme() for the rationale.
    files.set('.claude/context/README.md',    buildContextReadme());
    files.set('.claude/context/decisions.md', buildDecisionsSeed(projectName));
    files.set('.claude/context/plans/README.md', buildPlansReadme());

    return files;
}
