import * as fs   from 'fs';
import * as path from 'path';
import { Manifest } from '../generator';

// Only adds plugin scripts to the package.json generated by `nest new`.
// Dependencies are handled by running `npm install` directly in the project.
export function addPluginScripts(targetDir: string, manifests: Manifest[]): void {
    const pkgPath = path.join(targetDir, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));

    for (const manifest of manifests) {
        Object.assign(pkg.scripts, manifest.scripts);
    }

    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
}
